included:
    - ViteMaDose
    - ViteMaDosesTests
    - ViteMaDoseUITests
disabled_rules:
    - large_tuple
    - force_cast
    - todo
    - nesting
    - identifier_name
line_length: 200
file_length: 800
type_body_length: 500
